apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-mysql
  labels:
    app: boilerplate-mysql
spec:
  selector:
    matchLabels:
      app: boilerplate-mysql
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: boilerplate-mysql
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          imagePullPolicy: "IfNotPresent"

          envFrom:
          - secretRef:
              name: mysql-secret
          
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage 
          persistentVolumeClaim:
            claimName: mysql-pv-claim
