apiVersion: v1
kind: Service
metadata:
  name: boilerplate-redis
  labels:
    app: boilerplate-redis
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    app: boilerplate-redis
    tier: redis