apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-redis
  labels:
    app: boilerplate-redis
spec:
  selector:
    matchLabels:
      app: boilerplate-redis
      tier: redis
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: boilerplate-redis
        tier: redis
    spec:
      - image: redis
        name: redis
        imagePullPolicy: "IfNotPresent"

        envFrom:
        - secretRef:
            name: redis-secret

        ports:
        - containerPort: 6379
          name: redis

        volumeMounts:
          - mountPath: /data
            name: redis-persistent-storage
    volumes:
    - name: redis-persistent-storage
      persistentVolumeClaim:
        claimName: redis-pv-claim

        