// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	entity "arka/cmd/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUserByEmailOrPhone provides a mock function with given fields: ctx, data
func (_m *UserRepository) GetUserByEmailOrPhone(ctx context.Context, data string) (*entity.User, error) {
	ret := _m.Called(ctx, data)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUser provides a mock function with given fields: ctx, page, limit
func (_m *UserRepository) ListUser(ctx context.Context, page int64, limit int64) ([]*entity.User, error) {
	ret := _m.Called(ctx, page, limit)

	var r0 []*entity.User
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []*entity.User); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
